services:
  - type: web
    name: texty
    runtime: node
    rootDir: server
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_VERSION
        value: 20
      - key: JWT_SECRET
        generateValue: true
      - key: JWT_EXPIRY
        value: 7d
      - key: PG_SSL
        value: true
